[tool.poetry]
name = "python-script-for-twitter-giveaway"
version = "0.1.0"
description = ""
authors = ["Odacchi"]

[tool.poetry.dependencies]
python = "^3.10.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

